server:
  port: 8010
  
mybatis:
  config-location: classpath:mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.sct.springcloud.entity    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:com/sct/springcloud/dao/**/*.xml                       # mapper映射文件
    
spring:
  application:
    name: sct-project-service-one
#  cloud:                                                   # 从配置中心调用
#    config:
#      discovery:
#        enabled: true
#        serviceId: sct-project-config
#      profile: dev
#      fail-fast: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.223.128:3306/sctprojectonedb              # 数据库名称
    username: root
    password: Rtdl@123
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  redis:  ##redis连接信息
    host: 192.168.223.128
    password: Rtdl@123
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
  activemq: 
    user: activeAccount
    password: Rtdl@123
    broker-url: tcp://192.168.223.128:8161
    in-memory: true
    pool: 
      expiry-timeout: 10000 //过期时间
      idle-timeout: 30000 //链接时间
      max-connections: 50 //最大链接数
      enabled: false //连接池是否可用
  mail:
    host: smtp.163.com
    username: yushengjun2018@163.com
    password: itmayiedu644
    enable:  true
    smtp:
      auth: true
    starttls:
      enable: true
      required: true

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://localhost:7000/eureka
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      
  instance:
    instance-id: sct-project-service-one
    prefer-ip-address: true     #访问路径可以显示IP地址   