server: 
  port: 7777
 
spring: 
  application:
    name: sct-project-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
      defaultZone: http://localhost:7000/eureka  #如果需要用sct-project-eureka访问必须做端口映射
  instance:
    instance-id: sct-project-zuul-gateway
    prefer-ip-address: true 
#zuul: 
#  ignored-services: sct-project-service-one
#  prefix: /chenyang
#  ignored-services: "*"
#  routes: 
#    mydept.serviceId: sct-project-service-two
#    mydept.path: /myProject/**